export function buildFeedbackPrompt({ originals, revised }) {
  const section = (label, orig, rev) => {
    if (!rev) return `## ${label}\n(No revised version submitted — skip this skill.)\n`;
    return `## ${label}\n\n### ORIGINAL (generated by the app)\n${orig || '(empty)'}\n\n### REVISED (edited by the user)\n${rev}\n`;
  };

  return `You are analysing edits a user made to AI-generated job-application documents, so that future generations learn the user's preferences. You are a precise editor — do not invent preferences that are not evidenced by the edits.

For each of the three documents below, compare ORIGINAL vs REVISED and:
1. Write a short human-readable summary of what meaningfully changed (tone, structure, vocabulary, formatting, content added/removed, length). Ignore trivial whitespace or reordering that carries no signal.
2. Extract a small set of **durable style/content rules** a future writer should follow to produce output closer to the REVISED version from the start. Rules must be:
   - General enough to apply to future documents for different jobs (not specific to this role)
   - Concrete and directive (e.g., "Use active voice exclusively", "Never open cover letters with 'I am writing to...'", "Keep bullets under 20 words")
   - At most 5 rules per skill — return fewer if fewer edits were made
   - Empty array if the revised version is essentially identical to the original

${section('CV (skill: cv)', originals.cv, revised.cv)}

${section('Cover Letter (skill: coverLetter)', originals.coverLetter, revised.coverLetter)}

${section('LinkedIn Message (skill: linkedIn)', originals.linkedIn, revised.linkedIn)}

Return ONLY JSON in this exact shape — no prose, no markdown fences:
{
  "cv": { "summary": "...", "rules": ["...", "..."] },
  "coverLetter": { "summary": "...", "rules": ["...", "..."] },
  "linkedIn": { "summary": "...", "rules": ["...", "..."] }
}
`;
}
